@startmindmap

+[#OrangeRed] Zookeeper

++[#yellow] 基础

+++[#Pink] 核心功能
++++[#AliceBlue] 数据发布和订阅
++++[#AliceBlue] 命名服务

+++[#Pink] 节点类型
++++[#AliceBlue] 持久节点
+++++[#GhostWhite]_ 删除持久节点需要显式的调用 delete
++++[#AliceBlue] 临时节点
+++++[#GhostWhite]_ 会话因超时或发生异常而关闭
++++[#AliceBlue] 有序节点


+++[#Pink] 集群的角色
++++[#MediumSpringGreen] Leader
++++[#MediumSpringGreen] Follow
+++++[#LightGreen]_ 可以发起投票
++++[#MediumSpringGreen] Observer
+++++[#LightGreen]_ 不參与投票，只接收投票结果

+++[#Pink] 分布式共识算法

++++[#AliceBlue] 主流算法

+++++[#LightGreen] ZAB 原子广播协议
++++++[#LightBlue] Zookeeper Atomic Broadcast
+++++++[#Aquamarine]_ 用于构建高可用的分布式的数据主备系统

++++++[#LightBlue] 广播-两阶段提交的流程
+++++++[#Aquamarine]_ Leader 发起提案
+++++++[#Aquamarine]_ Follow 响应提案
+++++++[#Aquamarine]_ 响应过半数，Leader 提交议案

++++++[#LightBlue] 快速选举的流程
+++++++[#Aquamarine]_ 投票给自己，把投票消息发给其它机器
+++++++[#Aquamarine]_ 同时也在接受其他节点的投票
+++++++[#Aquamarine]_ 按照投票的优先级比较收到的选票和自己投出去的选票
+++++++[#Aquamarine]_ 每收集到一个投票后，查看已经收到的投票结果记录列表，看是否有节点能够达到一半以上的投票数。
+++++++[#Aquamarine]_ 如果有达到，则终止投票，宣布选举结束，更新自身状态。然后进行发现和同步阶段。否则继续收集投票

+++++[#LightGreen] Raft 协议
++++++[#LightBlue]_ 如果 Follow 内没有收到来自 Leader 的心跳，则会转化为 Candidate，主动发起选举
++++++[#LightBlue]_ 然后 Candidate 先投自己一票，向所有其他节点发起投票请求
++++++[#LightBlue]_ 如果发出去的投票请求得到了半数节点的成功回应，就会立即变身为 Leader
++++++[#LightBlue]_ 没选上的 Candidate 退回到 Follow 状态，接收 Leader 领导

+++++[#GhostWhite] Paxos 协议
++++++[#LightBlue]_ 太复杂

++++[#MediumSpringGreen] Zab 和 Raft 的区别
+++++[#LightGreen]_ 角色不同：Zk 引入了 Observer 的角色来提升性能
+++++[#LightGreen]_ 选举的时间不同：Zab 每个节点允许多次投票，只需要一轮
+++++[#LightGreen]_ 请求处理方式不同：Raft 直接和 Leader 交互

++++[#MediumSpringGreen] Zab 和 Raft 的联系
+++++[#LightGreen]_ 日志模型很像，都是超过半数节点完成复制之后，该命令才会被提交
+++++[#LightGreen]_ 主节点选举方面，半数节点确认之后的节点，才有可能成为新 Leader

+++[#Pink] 负载均衡算法

++++[#MediumSpringGreen] 原地址哈希法
++++[#MediumSpringGreen] 最小连接数法
++++[#AliceBlue]_ 轮询法
++++[#AliceBlue]_ 随机法
++++[#AliceBlue]_ 加权随机法

+++[#Pink] 应用
++++[#AliceBlue] 分布式 ID
++++[#MediumSpringGreen] 分布式锁


@endmindmap