@startmindmap

+[#OrangeRed] 分布式系统

++[#yellow] 微服务

+++[#Pink] 常见问题

++++[#MediumSpringGreen] 分布式锁

+++++[#LightGreen] Redis
++++++[#Aquamarine] 以商品 id 为分布式锁的 key，锁一个商品
++++++[#Aquamarine]_ 场景：保证扣库存数量准确，点击结算时，后端逻辑会查询库存和扣库存的 update 语句同时只有一条线程能够执行

+++++[#LightGreen] Zookeeper
++++++[#Aquamarine] 有序的临时子节点

++++[#MediumSpringGreen] 分布式事务
+++++[#LightGreen] RocketMQ
++++++[#Aquamarine] 事务消息

+++++[#LightGreen] Seata
++++++[#Aquamarine] 分布式事务框架

++++[#MediumSpringGreen] CAP
+++++[#LightGreen]_ Consistency / 一致性
+++++[#GhostWhite]_ Availability / 可用性
+++++[#LightGreen]_ Partition Tolerance / 分区容错性


++[#yellow] 分布式难题

+++[#Pink] 系统同步性
+++[#Pink] 幂等
+++[#Pink] 扩容
+++[#Pink] 唯一 ID
+++[#Pink] 网络因素
+++[#Pink] CAP 定律
++++[#MediumSpringGreen] 一致性
+++[#Pink] 共识算法
+++[#Pink] 分布式事务
++++[#MediumSpringGreen] 可靠消息
+++[#Pink] 分布式锁
+++[#Pink] 数据均衡分布问题
++++[#MediumSpringGreen] 一致性哈希
+++[#Pink] 可靠性
++++[#MediumSpringGreen] 几个 9 的指标







@endmindmap