@startmindmap

+[#OrangeRed] ElasticSearch

++[#yellow] 基本概念

+++[#Pink] 索引

++++[#AliceBlue] mapping / 映射

++++[#MediumSpringGreen] 反向索引 / 倒排索引
+++++_ 单词在文档中存储位置的映射
+++++_ 根据关键字，查找文档 id
+++++_ 存储形式：单词 - 文档矩阵

++++[#AliceBlue] 正向索引
+++++_ 扫描索引库中的所有文档，查找是否含有关键词

++++[#AliceBlue] 聚合索引


+++[#Pink] 查询

++++[#MediumSpringGreen] primary shard / 主分片
+++++_ 默认 5 个
+++++_ 每个分片最好不超过 30 GB

++++[#MediumSpringGreen] replica shard / 副本
+++++_ 默认 1 个

++++[#AliceBlue] scroll / 游标查询


+++[#Pink] Lucene

++++[#MediumSpringGreen] index / 索引
+++++_ 相似特性的文档的集合
++++[#MediumSpringGreen] shard / 分片
++++[#MediumSpringGreen] segment / 段文件
+++++_ 分片下的索引文件被拆分成的多个子文件
++++[#AliceBlue] document / 文档
++++[#AliceBlue] field / 字段
++++[#MediumSpringGreen] term / 词项
+++++_ 文本中词
++++[#MediumSpringGreen] token / 词条
+++++_ 词项在字段中的一次出现，包括词项的文本、开始和结束的位移、类型等信息



@endmindmap