@startmindmap

+[#OrangeRed] MySQL

++[#yellow] 提高

+++[#Pink] 性能优化：开发

++++[#MediumSpringGreen] SQL 优化
+++++[#LightGreen] SQL 优化
++++++[#LightBlue]_ 不要使用 select *
++++++[#LightBlue]_ where 字段加索引
++++++[#LightBlue]_ limit 分页的参数不应过大
++++++[#LightBlue]_ 用小结果集驱动大结果集

+++++[#LightGreen] 执行计划
++++++[#Aquamarine] EXPLAIN 分析查询的执行计划
+++++++[#Aquamarine]_ type
+++++++[#Aquamarine]_ Extra
+++++++[#Aquamarine]_ key
+++++++[#Aquamarine]_ rows

+++++[#LightGreen] 慢 SQL 的定位和排查
++++++[#Aquamarine] 通过慢查询日志和慢查询日志分析工具得到有问题的 SQL 列表

+++++[#LightGreen] 系统资源
++++++[#Aquamarine] performance_schema
++++++[#Aquamarine] show profiles：排查死锁，定位慢 SQL
++++++[#Aquamarine]_ show processlist
++++++[#Aquamarine]_ show 命令查询系统状态及系统变量


++++[#MediumSpringGreen] 索引优化

+++++[#LightGreen] 字段建索引
++++++[#Aquamarine]_ 经常用于 where 查询的字段要建索引
++++++[#Aquamarine]_ 经常用于 join on 的字段要建索引
++++++[#Aquamarine]_ 经常用于 order by 的字段要建索引

+++++[#LightGreen] 选择索引类型
++++++[#Aquamarine]_ 选择唯一性索引
++++++[#Aquamarine]_ 尽量使用组合索引
++++++[#Aquamarine]_ 尽量使用前缀来索引

+++++[#LightGreen] 限制索引
++++++[#Aquamarine]_ 限制索引的数目（增删改要更新索引，索引树多了占空间）
++++++[#Aquamarine]_ 删除不再使用或者很少使用的索引


++++[#MediumSpringGreen] 表优化

+++++[#LightGreen] 表设计
++++++[#Aquamarine]_ 冗余字段
++++++[#Aquamarine]_ 以空间换时间

+++++[#LightGreen] 表分区
++++++[#Aquamarine]_ 大表分区
++++++[#Aquamarine]_ 大小超过 2G

+++++[#LightGreen] 分库分表
++++++[#Aquamarine]_ 垂直拆分
+++++++[#Aquamarine]_ 按业务拆分
++++++[#Aquamarine]_ 水平拆分
+++++++[#Aquamarine]_ 按主键哈希值取模
+++++++[#Aquamarine]_ 时间维度拆分
+++++++[#LightGreen] 水平分表算法
++++++++[#Aquamarine]_ Hash 算法
++++++++[#Aquamarine]_ 一致性 Hash 算法
+++++++++[#Aquamarine]_ Hash 环
+++++++++[#Aquamarine]_ 顺时针找最近的节点
+++++++++[#Aquamarine]_ 数据迁移的代价更小


+++[#Pink] 性能优化：DBA

++++[#MediumSpringGreen] 配置优化

+++++[#LightGreen] my.cnf
++++++[#Aquamarine]_ 5.7 版本默认的最大连接数是 151 个
++++++[#Aquamarine]_ binlog 日志，默认是不开启
++++++[#Aquamarine]_ 缓存池 bufferpoll 的默认大小配置


++++[#MediumSpringGreen] 架构优化

+++++[#LightGreen] 主从集群
++++++[#Aquamarine]_ 保证服务高可用

+++++[#LightGreen] 读写分离
++++++[#Aquamarine]_ 主库负责写
++++++[#Aquamarine]_ 从库负责读

+++++[#LightGreen] 热点数据，引入缓存
++++++[#Aquamarine]_ Redis


++++[#MediumSpringGreen] 硬件及操作系统层面优化

+++++[#LightGreen] 硬件
++++++[#Aquamarine]_ CPU
++++++[#Aquamarine]_ 可用内存大小
++++++[#Aquamarine]_ 磁盘读写速度
++++++[#Aquamarine]_ 网络带宽
+++++[#LightGreen] 操作系统
++++++[#Aquamarine]_ 应用文件句柄数
++++++[#Aquamarine]_ 操作系统网络的配置




'+++[#Pink] 常见问题


++[#yellow] 2

+++[#Pink] 3

++++[#MediumSpringGreen] 4
+++++[#LightGreen] 5
++++++[#Aquamarine] 6
+++++++[#Aquamarine]_ 7
++++++[#PowderBlue] 6
+++++++[#PowderBlue]_ 7
++++[#AliceBlue] 4
+++++[#GhostWhite] 5



@endmindmap