@startmindmap

+[#OrangeRed] web

++[#yellow] Vue.js

+++[#Pink] 面试

++++[#MediumSpringGreen] 常考
+++++[#LightGreen] v-if 和 v-for 优先级
++++++[#Aquamarine] v-for 优先级高，基于性能的考虑，建议 v-for 前先 v-if
+++++[#LightGreen] 单向数据和双向数据流绑定
++++++[#Aquamarine] 单向：v-bind、Vuex
++++++[#Aquamarine] 双向：v-model
+++++[#LightGreen] Vuex 修改数据
++++++[#Aquamarine] mutations
+++++[#LightGreen] 性能优化
++++++[#Aquamarine] 交互：懒加载
++++++[#Aquamarine] 瀑布流
+++++[#LightGreen] Web 安全问题
++++++[#Aquamarine] sql 注入
++++++[#Aquamarine] xss
++++++[#Aquamarine] require 第三方包
+++++[#LightGreen] mvvm 和 mvc
++++++[#Aquamarine] MVVM（Model-View-ViewModel 视图层-模型层-视图模型层）采用双向数据绑定，Model-View 隔离
+++++++[#PowderBlue] View：用户界面
+++++++[#PowderBlue] ViewModel：业务逻辑
+++++++[#PowderBlue] Model：数据结构
+++++++[#PowderBlue] View 中数据变化将反映到 ViewModel 上，Model 中数据变化也会展示在 View 上
++++++[#Aquamarine] MVC（Model-View-Controller 视图层-模型层-控制层）采用单向数据流
+++++++[#PowderBlue] Controller 接收用户侧 或者 View 端的指令，把 Model 返回给 View
+++++[#LightGreen] ajax
+++++[#LightGreen] 进阶算法

++++[#MediumSpringGreen] 常客

+++++[#LightGreen] 实例生命周期
++++++[#Aquamarine] 6




+++[#Pink] 基础

++++[#MediumSpringGreen] 项目结构
+++++[#LightGreen]_ dist | 编译目录
+++++[#LightGreen]_ locales | I18n文件
+++++[#LightGreen]_ mock | 模拟数据文件
+++++[#LightGreen]_ public | 网站公共目录
+++++[#LightGreen]_ src | 源码目录
++++++[#Aquamarine]_ App.vue | 页面入口
++++++[#Aquamarine]_ assets | 静态资源
++++++[#Aquamarine]_ components | 公共组件
++++++[#Aquamarine]_ directives | 指令库
++++++[#Aquamarine]_ enum | 全局枚举文件
++++++[#Aquamarine]_ hooks | 自定义 hooks
++++++[#Aquamarine]_ layouts | 项目布局文件
++++++[#Aquamarine]_ main.ts | 程序入口
++++++[#Aquamarine]_ model | 模型定义类型文件
++++++[#Aquamarine]_ plugins | 插件文件
++++++[#Aquamarine]_ router | 路由文件
++++++[#Aquamarine]_ store | 全局状态
++++++[#Aquamarine]_ style | 全局样式
++++++[#Aquamarine]_ utils | 工具库
++++++[#Aquamarine]_ views | 视图
+++++[#LightGreen]_ types | ts 类型定义


++++[#MediumSpringGreen] 核心

+++++[#LightGreen] 模板语法
++++++[#Aquamarine]_ template 模板
++++++[#Aquamarine]_ 双花括号
++++++[#Aquamarine]_ 元素值：id 捆绑
++++++[#Aquamarine]_ 生命周期函数：before、after

+++++[#LightGreen] 事件处理
++++++[#Aquamarine]_ 元素事件：方法名捆绑

+++++[#LightGreen] 绑定
++++++[#Aquamarine]_ 类和样式绑定
++++++[#Aquamarine]_ 表单输入绑定
++++++[#Aquamarine]_ 条件渲染
++++++[#Aquamarine]_ 列表渲染
++++++[#Aquamarine]_ 实例生命周期

+++++[#LightGreen] 组件
++++++[#Aquamarine]_ 组件
++++++[#Aquamarine]_ 单文件组件
++++++[#Aquamarine]_ 计算属性
++++++[#Aquamarine]_ 侦听器
++++++[#Aquamarine]_ Vuex



++[#yellow] Element UI








+++[#Pink] 3

++++[#MediumSpringGreen] 4

+++++[#LightGreen] 5
++++++[#Aquamarine] 6
+++++++[#PowderBlue] 7

++++[#AliceBlue] 4
+++++[#GhostWhite]_ 5
++++++[#PowderBlue]_ 6
+++++++[#PowderBlue]_ 7


'https://www.ruanyifeng.com/blog/2015/02/mvcmvp_mvvm.html



@endmindmap