@startmindmap

+[#OrangeRed] 算法题

++[#yellow] 算法

+++[#Pink] 基本思想

++++[#MediumSpringGreen] 递归 / Recursion
+++++_ 深度优先
+++++_ 判断结束条件

++++[#MediumSpringGreen] 回溯
+++++_ 前置操作
+++++_ 递归（在递归中循环）
+++++_ 后置操作（撤销前置操作）

++++[#MediumSpringGreen] 贪心
+++++_ 及时舍弃，只要第一

++++[#MediumSpringGreen] 分治
++++[#MediumSpringGreen] 双指针 / Two Pointers
++++[#MediumSpringGreen] 快慢指针 / Fast & Slow Pointers

++++[#MediumSpringGreen] 深度优先搜索 / Depth First Search
+++++_ 递归
+++++_ 未知深度

++++[#MediumSpringGreen] 广度优先搜索 / Breath First Search
+++++_ 数组（多维）
+++++_ 多层循环
+++++_ 可能需要队列


++++[#AliceBlue] 位运算
++++[#AliceBlue] 穷举
++++[#AliceBlue] 模拟

++++[#MediumSpringGreen] 动态规划 / Dynamic Programming
+++++[#GhostWhite] 套路
++++++_ 数组 / 二维数组
++++++_ 数组类型一般是整型或者布尔，用来存储长度或状态
+++++[#GhostWhite] 题型
++++++_ 背包问题
++++++_ 最长子序列
++++++_ 计数问题
+++++[#GhostWhite] 分类
++++++_ Recursion
++++++_ Top+Down
++++++_ Bottom+Up

++++[#MediumSpringGreen] 滑动窗口 / Sliding Window
+++++_ 两层循环
+++++_ 右指针遍历滑动，左指针在二层循环（while）中跟随滑动


+++[#Pink] 算法技巧

++++[#AliceBlue] 记忆化搜索
++++[#AliceBlue] 并查集
++++[#AliceBlue] 前缀和
++++[#AliceBlue] 扫描线

++++[#AliceBlue] 多线程
++++[#AliceBlue] 设计模式


+++[#Pink] 模式

++++[#MediumSpringGreen] 合并区间 / Merge Intervals
++++[#AliceBlue] 双堆 / Two Heaps
++++[#AliceBlue] 子集 / Subsets
++++[#MediumSpringGreen] 前 K 个 / K’ Elements / 堆 / PriorityQueue
++++[#AliceBlue] 多路归并 / K-way merge
++++[#AliceBlue] 背包 / Knapsack
++++[#AliceBlue] 子序列
++++[#AliceBlue] 股票
++++[#AliceBlue] 打家劫舍


+++[#Pink] 图算法

++++[#MediumSpringGreen] 最小生成树
++++[#MediumSpringGreen] 最短路径
++++[#AliceBlue] 拓扑排序 / Topological Sort
++++[#AliceBlue] 关键路径
++++[#AliceBlue] 邻接矩阵
++++[#AliceBlue] 邻接表

+++[#Pink] 字符串匹配算法

++++[#MediumSpringGreen] Trie 算法 / 字典树
++++[#AliceBlue] BF 算法 / 暴力匹配
++++[#AliceBlue] BM 算法
++++[#AliceBlue] KMP 算法

+++[#Pink] 排序算法 / Sort

++++[#LightBlue] O(n^2)
+++++[#MediumSpringGreen] 冒泡排序
+++++[#MediumSpringGreen] 选择排序
+++++[#MediumSpringGreen] 插入排序
+++++[#AliceBlue] 希尔排序
++++[#LightBlue] O(n log n)
+++++[#MediumSpringGreen] 归并排序
+++++[#MediumSpringGreen] 堆排序
+++++[#AliceBlue] 快速排序
++++[#LightBlue] O(n + k)
+++++[#AliceBlue] 桶排序
+++++[#AliceBlue] 基数排序
+++++[#AliceBlue] 计数排序

+++[#Pink] 查找算法 / Search

++++[#LightBlue] O(log 2n)
+++++[#MediumSpringGreen] 二分查找 / Binary Search
+++++[#AliceBlue] 二叉查找树
+++++[#MediumSpringGreen] 红黑树
+++++[#AliceBlue] B 树
+++++[#MediumSpringGreen] B+ 树
++++[#LightBlue] O(n)
+++++[#AliceBlue] 顺序查找
++++[#LightBlue] O(1)
+++++[#AliceBlue] 哈希查找


@endmindmap
