@startmindmap

+[#OrangeRed] JVM

++[#yellow] ClassLoader / 类加载器

***[#Pink]: 类的生命周期（五）
/ 执行字节码的过程
/ 类加载的过程;
++++[#AliceBlue] 加载
++++[#MediumSpringGreen] 链接（三）
+++++[#LightGreen] 验证
++++++_ 字节码验证，格式和行为合法
+++++[#LightGreen] 准备
++++++_ 类装备，准备必须的数据结构
+++++[#LightGreen] 解析
++++++_ 装入器装入类中引用的其他类
++++[#MediumSpringGreen] 初始化
+++++[#LightGreen] 初始化的顺序
++++[#AliceBlue] 使用
++++[#AliceBlue] 卸载


+++[#Pink]  加载器的等级（三）
++++[#MediumSpringGreen] BootStrap ClassLoader / 启动类加载器
+++++[#AliceBlue]_ 负责加载 JDK 中的核心类库
++++[#MediumSpringGreen] Extension ClassLoader / 扩展类加载器
+++++[#AliceBlue]_ 负责加载 Java 的扩展类库
++++[#MediumSpringGreen] App ClassLoader / 系统类加载器
+++++[#AliceBlue]_ 负责加载 classpath 目录下的所有 jar 和 class 文件


+++[#Pink]  类加载的原理
++++[#MediumSpringGreen] 双亲委派机制
+++++[#AliceBlue]_ 可以避免重复加载
+++++[#AliceBlue]_ 可以防止核心 class 被篡改


@endmindmap