@startmindmap

+[#OrangeRed] Collection

++[#yellow] List

+++[#Pink] 列表

++++[#MediumSpringGreen] ArrayList
+++++[#LightGreen] 扩容
++++++[#Aquamarine] Arrays.copyOf()
+++++[#MediumSpringGreen]_ 底层是数组，动态的 Object []
+++++[#MediumSpringGreen]_ CopyOnWriteArrayList 才能保证线程安全（适合多写少读）

++++[#MediumSpringGreen] LikedList
+++++[#LightGreen] 双向链表
++++++[#Aquamarine] Node




++[#yellow] Set

+++[#Pink] 集合

++++[#MediumSpringGreen] HashSet
+++++[#LightGreen]_ Hash 算法
+++++[#LightGreen] 底层是 HashMap，返回 keys

++++[#MediumSpringGreen] TreeSet
+++++[#LightGreen] 基于 TreeMap 的 NavigableSet 实现
+++++[#LightGreen] 用红黑树来存储数据




++[#yellow] Queue

+++[#Pink] 队列

++++[#MediumSpringGreen] PriorityQueue
+++++[#LightGreen] 底层是堆






++[#yellow] 2

+++[#Pink] 3

++++[#MediumSpringGreen] 4
+++++[#LightGreen] 5
++++++[#Aquamarine] 6
+++++++[#Aquamarine]_ 7





@endmindmap