@startmindmap

+[#OrangeRed] 钱包

++[#yellow] 业务

+++[#Pink] 授信

+++[#Pink] 申请贷款流程

++++[#AliceBlue] 申请贷款
++++[#AliceBlue] 申请单
++++[#MediumSpringGreen] 异步筛查
+++++[#LightGreen] 项目状态、产品状态
+++++[#LightGreen] 黑名单
+++++[#LightGreen] 金额、期限、利率、还款方式
++++[#MediumSpringGreen] 风控评分
++++[#MediumSpringGreen] 人工审批
++++[#MediumSpringGreen] 电子签章
++++[#AliceBlue] 借据生成
++++[#AliceBlue] 保存借据
++++[#MediumSpringGreen] 放款申请
++++[#AliceBlue] 保存放款记录
++++[#AliceBlue] 放款成功
++++[#MediumSpringGreen] 生成还款计划
++++[#AliceBlue] 保存还款计划

+++[#Pink] 还款流程

++++[#MediumSpringGreen] 线上还款
++++[#MediumSpringGreen] 登记线下还款

+++[#Pink] 贷后变更

++++[#MediumSpringGreen] 变更扣款日
++++[#MediumSpringGreen] 变更还款账户
++++[#MediumSpringGreen] 减免息费

+++[#Pink] 代偿
+++[#Pink] 回购
+++[#Pink] 登记催收


@endmindmap