@startmindmap

+[#OrangeRed] Linux

++[#yellow] IO

+++[#Pink] IO 分类
++++[#AliceBlue] IO / input-output
+++++_ 读写操作
++++[#AliceBlue] BIO / Blocking io / 同步阻塞
+++++_ 线程必须等待 io 执行完成
++++[#MediumSpringGreen] NIO / Non-blocking IO / 同步非阻塞
+++++_ 线程无需等待，但是需要轮询 io 的执行结果
++++[#AliceBlue] AIO / Asynchronous IO / 异步非阻塞
+++++_ 线程无需等待，io 执行完之后会收到系统通知

+++[#Pink] IO 多路复用

++++[#AliceBlue] select
+++++[#LightGreen] 睡眠队列
+++++[#LightGreen]_ 遍历慢
+++++[#LightGreen]_ fd 数量有限（1024）

++++[#AliceBlue] poll
+++++[#Aquamarine]_ 遍历慢

++++[#MediumSpringGreen] epoll
+++++[#LightGreen] 红黑树
+++++[#LightGreen] 就绪列表


++[#yellow] shell

+++[#Pink] 基础

++++[#MediumSpringGreen] 常用命令
+++++[#LightGreen] top
++++++[#Aquamarine]_ 当前时间、上一次开机的时间、当前在线用户数、CPU 负载信息
++++++[#Aquamarine]_ 任务数量，运行的数量、睡眠的数量、停止的数量、僵死的数量
++++++[#Aquamarine]_ CPU 总体信息
++++++[#Aquamarine]_ 内存：物理内存总量、使用的物理内存量、空闲的物理内存量、用作内核缓存的物理内存量
++++++[#Aquamarine]_ 交换空间：交换区总量、使用的交换区量、空闲的交换区量、缓冲交换区总量
+++++[#GhostWhite]_ pidstat
+++++[#GhostWhite]_ grep
+++++[#GhostWhite]_ cat grep
+++++[#GhostWhite]_ kill
+++++[#GhostWhite]_ ftp
+++++[#GhostWhite]_ telnet
+++++[#GhostWhite]_ ping



@endmindmap