@startmindmap

+[#OrangeRed] Linux

++[#yellow] IO

+++[#Pink] IO 分类
++++[#AliceBlue] IO / input-output
+++++_ 读写操作
++++[#AliceBlue] BIO / Blocking io / 同步阻塞
+++++_ 线程必须等待 io 执行完成
++++[#MediumSpringGreen] NIO / Non-blocking IO / 同步非阻塞
+++++_ 线程无需等待，但是需要轮询 io 的执行结果
++++[#AliceBlue] AIO / Asynchronous IO / 异步非阻塞
+++++_ 线程无需等待，io 执行完之后会收到系统通知

+++[#Pink] IO 多路复用

++++[#AliceBlue] select
+++++[#Aquamarine] 睡眠队列
+++++[#Aquamarine]_ 遍历慢
+++++[#Aquamarine]_ fd 数量有限（1024）

++++[#AliceBlue] poll
+++++[#Aquamarine]_ 遍历慢

++++[#MediumSpringGreen] epoll
+++++[#LightGreen] 数据结构
++++++[#Aquamarine] 红黑树
++++++[#Aquamarine] 就绪列表


++[#yellow] shell

+++[#Pink] 基础

++++[#MediumSpringGreen] 常用命令
+++++[#GhostWhite]_ top
+++++[#GhostWhite]_ pidstat
+++++[#GhostWhite]_ grep
+++++[#GhostWhite]_ cat grep
+++++[#GhostWhite]_ kill
+++++[#GhostWhite]_ ftp
+++++[#GhostWhite]_ telnet
+++++[#GhostWhite]_ ping



@endmindmap