@startmindmap

+[#OrangeRed] 数字化

++[#yellow] 业务

+++[#Pink] 数据

++++[#LightYellow] 基本数据
+++++[#LightGreen] 国家
+++++[#LightGreen] 地区

++++[#LightYellow] 行业数据
+++++[#LightGreen] 通信行业数据
+++++[#LightGreen] 互联网行业数据

++++[#MediumSpringGreen] 产品数据
+++++[#GhostWhite] 可以用来交付的方案


+++[#Pink] 应用

++++[#MediumSpringGreen] 报告型
+++++[#GhostWhite] 数据报告

++++[#MediumSpringGreen] 使用型
+++++[#GhostWhite] 数据引用


+++[#Pink] 解决方案

++++[#LightYellow] 大型项目
++++[#LightYellow] 成功案例
+++++[#GhostWhite] 可以用来交付的方案

++++[#MediumSpringGreen] 内容
+++++[#GhostWhite] 多级菜单
+++++[#GhostWhite] 应用引用
+++++[#GhostWhite] 多种数据格式：地图、视频、图片、胶片、文档、原始数据库文件


++[#yellow] 技术

+++[#Pink] 架构

++++[#LightYellow] Nginx
++++[#MediumSpringGreen] Zookeeper
++++[#MediumSpringGreen] Dubbo
++++[#MediumSpringGreen] RocketMQ
++++[#MediumSpringGreen] Redis
++++[#MediumSpringGreen] Spring Cloud
++++[#MediumSpringGreen] Zuul 网关

+++++[#LightGreen] Redis
++++++[#Aquamarine] 登录信息、token
++++++[#Aquamarine] 手机验证码
++++++[#Aquamarine] 地区编码

++++++[#Aquamarine] 千人千面的推荐数据
++++++[#Aquamarine] 分布式锁

+++++[#LightGreen] ElasticSearch
++++++[#Aquamarine] 标准数据


++++[#MediumSpringGreen] 数据库
+++++[#LightGreen] Oracle
+++++[#LightGreen] MySQL



++[#yellow] 2

+++[#Pink] 3

++++[#MediumSpringGreen] 4
+++++[#LightGreen] 5
++++++[#Aquamarine] 6
+++++++[#Aquamarine]_ 7
++++++[#PowderBlue] 6
+++++++[#PowderBlue]_ 7
++++[#AliceBlue] 4
+++++[#GhostWhite] 5



@endmindmap