@startmindmap

+[#OrangeRed] 钱包

++[#yellow] 业务

+++[#Pink] 申请

++++[#MediumSpringGreen] 申请授信

++++[#MediumSpringGreen] 申请贷款

+++++[#GhostWhite] 申请单
+++++[#LightGreen] 异步筛查
++++++[#Aquamarine] 项目状态、产品状态
++++++[#Aquamarine] 黑名单
++++++[#Aquamarine] 金额、期限、利率、还款方式
+++++[#LightGreen] 风控评分
++++++[#Aquamarine] 人工审批
+++++[#LightGreen] 电子签章
+++++[#GhostWhite] 借据生成
++++++[#Aquamarine] 保存借据

++++[#MediumSpringGreen] 放款流程

+++++[#LightGreen] 放款申请
+++++[#GhostWhite] 保存放款记录
+++++[#GhostWhite] 放款成功
+++++[#LightGreen] 生成还款计划
+++++[#GhostWhite] 保存还款计划

++++[#MediumSpringGreen] 还款流程

+++++[#LightGreen] 线上还款
+++++[#LightGreen] 登记线下还款


+++[#Pink] 贷后

++++[#MediumSpringGreen] 贷后变更

+++++[#LightGreen] 变更扣款日
+++++[#LightGreen] 变更还款账户
+++++[#LightGreen] 减免息费

++++[#MediumSpringGreen] 代偿
++++[#MediumSpringGreen] 回购
++++[#MediumSpringGreen] 登记催收


@endmindmap