@startmindmap

+[#OrangeRed] MySQL

++[#yellow] 基础

+++[#Pink] 三大范式
++++[#MediumSpringGreen] 字段都具备原子性；表需要有一个主键
++++[#MediumSpringGreen] 非主键字段完全依赖主键，不能产生部分依赖
++++[#MediumSpringGreen] 非主键字段不能依赖于其他非主键字段，非主键字段和主键之间不能产生传递依赖
++++[#AliceBlue] 通过增加冗余或重复的数据来提高数据库的读性能

+++[#Pink] 语句执行流程

++++[#MediumSpringGreen] 客户端提交 SQL（使用连接池的连接，通过数据库驱动访问服务端）
++++[#MediumSpringGreen] 服务端获得 SQL
++++[#MediumSpringGreen] 解析器解析 SQL，生成解析树
++++[#MediumSpringGreen] 优化器优化 SQL（执行计划缓存）
++++[#MediumSpringGreen] 执行器从数据库引擎获取数据（数据缓存）
++++[#MediumSpringGreen] 服务端返回查询结果


@endmindmap