@startmindmap

+[#OrangeRed] Spring-Cloud

++[#yellow] 实现方式

+++[#Pink] Spring Cloud Alibaba
++++[#MediumSpringGreen] 注册中心
+++++[#GhostWhite] Nacos Discovery
++++[#AliceBlue] 分布式配置
+++++[#GhostWhite] Nacos Config
++++[#MediumSpringGreen] 服务调用
+++++[#GhostWhite] Dubbo
++++[#AliceBlue] 负载均衡
+++++[#GhostWhite] Spring Cloud Loadbalancer
++++[#AliceBlue] 服务熔断与降级
+++++[#GhostWhite] Sentinel
++++[#AliceBlue] 服务网关
+++++[#GhostWhite] Spring Cloud Gateway
++++[#AliceBlue] 消息队列
+++++[#GhostWhite] RocketMQ
++++[#AliceBlue] 分布式事务
+++++[#GhostWhite] Seata


+++[#Pink] Spring Cloud Netflix
++++[#AliceBlue]_ Eureka
++++[#AliceBlue]_ Feign
++++[#AliceBlue]_ Hystrix
++++[#AliceBlue]_ Zuul
++++[#AliceBlue]_ Config
++++[#AliceBlue]_ Ribbon
++++[#AliceBlue]_ RabbitMQ


++[#yellow] 常见问题

+++[#Pink] 三剑客

++++[#MediumSpringGreen] 负载均衡
+++++[#GhostWhite] RandomRule：随机
+++++[#GhostWhite] RoundRobinRule：轮询
+++++[#GhostWhite] WeightedResponseTimeRule：权重

++++[#MediumSpringGreen] 服务降级
+++++[#GhostWhite] 超时降级
+++++[#GhostWhite] 失败次数降级
+++++[#GhostWhite] 故障降级

++++[#MediumSpringGreen] 服务熔断
+++++[#GhostWhite] 自动熔断时机
+++++[#GhostWhite] 熔断恢复的条件
+++++[#GhostWhite] 区分核心和非核心功能



@endmindmap